export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_JOGS_ERROR = 'FETCH_JOGS_ERROR';
export const FETCH_JOGS_SUCCESS = 'FETCH_JOGS_SUCCESS';
export const SET_JOG = 'SET_JOG';

export const SET_FILTER_START = 'SET_FILTER_START';
export const SET_FILTER_END = 'SET_FILTER_END';
export const SET_TOGGLE_FORM = 'SET_TOGGLE_FORM';
